---
extends:
 - 'react-app'

env:
 node: true
 browser: true

rules:
 class-methods-use-this:
   - error
   -
     exceptMethods:
     - render
     - getInitialState
     - getDefaultProps
     - getChildContexts
     - componentWillMount
     - componentDidMount
     - componentWillReceiveProps
     - shouldComponentUpdate
     - componentWillUpdate
     - componentDidUpdate
     - componentWillUnmount
